### ISSUE TITLE
router bit?

### ISSUE THREAD

**Issue by dragosrotaru** [VladLunachev/BeamCNC#2]
hey Vlad , so I implemented the design. I have a bunch of feedback and ideas but I don't have time at the moment as I need to move in a few days.... I was wondering what kind of bit do you use? I can't get a good result using any of the router bits I tried. the only options I see:

1. use a 5/16 (8mm) collet and a Brad point bit

2. use a 1/2 collet and a 5/16 reducer and a Brad point bit

3. use a 1/4 Brad point bit then use a    5/16 double flute straight bit with a 1/4 shank

4. use a 3/8 collet with a Brad point bit

thoughts?

![20211216_101749.jpg](https://user-images.githubusercontent.com/7482137/146398516-71dd9bc3-886a-45ed-83cd-0f2fbd5c66b9.jpg)

**Comment by vladlunachev** [comment]
brad-point bit, because of sharp point which slightly follows the wood grain results in offset holes.
I use a simple sharp metal drill bit 8mm. you can see it in some [photos](https://drive.google.com/drive/folders/1RdrnFPg5XGlIHzHOro5i5P0a59IhgZBA).
